export const indeedSearchUrl = `https://www.indeed.com/jobs`;

export enum Roles {
  SOFTWARE_ENGINEER = "software engineer",
  FRONTEND_DEVELOPER = "frontend developer",
  BACKEND_DEVELOPER = "backend developer",
  FULLSTACK_DEVELOPER = "fullstack developer",
  MOBILE_DEVELOPER = "mobile developer",
  DEVOPS_ENGINEER = "devops engineer",
  CLOUD_ENGINEER = "cloud engineer",
  DATA_ENGINEER = "data engineer",
  DATA_SCIENTIST = "data scientist",
  MACHINE_LEARNING_ENGINEER = "machine learning engineer",
  AI_ENGINEER = "ai engineer",
  QA_ENGINEER = "qa engineer",
  TEST_AUTOMATION_ENGINEER = "test automation engineer",
  GAME_DEVELOPER = "game developer",
  UNITY_DEVELOPER = "unity developer",
  UNREAL_ENGINE_DEVELOPER = "unreal engine developer",
  PRODUCT_MANAGER = "product manager",
  PROJECT_MANAGER = "project manager",
  UI_UX_DESIGNER = "ui/ux designer",
  GRAPHIC_DESIGNER = "graphic designer",
  SYSTEM_ADMINISTRATOR = "system administrator",
  NETWORK_ENGINEER = "network engineer",
  SECURITY_ENGINEER = "security engineer",
  BUSINESS_ANALYST = "business analyst",
  TECHNICAL_WRITER = "technical writer",
}
